[package]
name = "aoa"
version = "0.1.0"
authors = ["Zero <nick@zero.dev>"]
edition = "2018"
license = "MIT"
description = "Android Open Accessory Protocol"

[dependencies]
rusb = "0.6"
byteorder = "1.3"
thiserror = "1.0"

[features]
aoa2 = []
